# Generated by Django 3.2.4 on 2021-07-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='name',
            field=models.CharField(default='unnamed_func', max_length=200),
            preserve_default=False,
        ),
    ]
