# Generated by Django 3.2.4 on 2021-08-26 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assembly",
            name="as_opts",
        ),
    ]
