# Generated by Django 3.2.4 on 2021-08-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assembly',
            old_name='compiler',
            new_name='arch',
        ),
    ]
