# Generated by Django 3.2.4 on 2021-08-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_rename_compiler_assembly_arch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='compiler',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
