# Generated by Django 3.2.6 on 2021-08-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_remove_assembly_as_opts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_user_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_load_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
