# Generated by Django 3.2.6 on 2021-08-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_remove_assembly_as_opts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_user_id',
            field=models.TextField(blank=True),
        ),
    ]
