# Generated by Django 3.2.6 on 2021-08-27 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_auto_20210827_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_load_time',
            field=models.DateTimeField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_user_id',
            field=models.TextField(null=True),
        ),
    ]
