# Generated by Django 3.2.4 on 2021-09-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_github_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratch',
            name='diff_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
