# Generated by Django 3.2.4 on 2021-08-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_auto_20210823_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilation',
            name='as_opts',
        ),
        migrations.RemoveField(
            model_name='compilation',
            name='cpp_opts',
        ),
        migrations.RemoveField(
            model_name='scratch',
            name='as_opts',
        ),
        migrations.RemoveField(
            model_name='scratch',
            name='cpp_opts',
        ),
    ]
