# Generated by Django 3.2.4 on 2021-07-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_auto_20210705_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilerconfiguration',
            name='shortname',
            field=models.CharField(max_length=50),
        ),
    ]
