# Generated by Django 3.2.4 on 2021-10-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_rename_arch_scratch_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratch',
            name='max_score',
            field=models.IntegerField(default=-1),
        ),
    ]
