# Generated by Django 3.2.4 on 2021-07-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_auto_20210705_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompilerConfiguration',
        ),
    ]
