# Generated by Django 3.2.4 on 2021-07-05 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_delete_compilerconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompilerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=50)),
                ('flags', models.CharField(max_length=100)),
                ('compiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.compiler')),
            ],
        ),
    ]
