# Generated by Django 3.2.4 on 2021-10-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_scratch_max_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scratch',
            name='original_context',
        ),
    ]
