# Generated by Django 3.2.4 on 2021-10-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_remove_scratch_original_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compilation',
            old_name='cc_opts',
            new_name='compiler_flags',
        ),
        migrations.RenameField(
            model_name='scratch',
            old_name='cc_opts',
            new_name='compiler_flags',
        ),
    ]
