# Generated by Django 3.2.4 on 2021-07-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_auto_20210705_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.scratch'),
        ),
    ]
