# Generated by Django 3.2.4 on 2021-12-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0011_alter_scratch_diff_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scratch",
            name="name",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
