# Generated by Django 3.2.4 on 2021-07-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_alter_scratch_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratch',
            name='owner',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
