# Generated by Django 4.0 on 2021-12-26 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_alter_scratch_diff_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.profile')),
            ],
        ),
    ]
