# Generated by Django 3.2.4 on 2021-07-05 07:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_alter_scratch_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scratch',
            name='submission_time',
        ),
        migrations.AddField(
            model_name='scratch',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('source_code', models.TextField()),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.assembly')),
                ('compiler_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.compilerconfiguration')),
            ],
        ),
    ]
