# Generated by Django 3.2.4 on 2021-07-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_auto_20210705_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scratch',
            name='compiler',
        ),
        migrations.AddField(
            model_name='scratch',
            name='compiler_config',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='coreapp.compilerconfiguration'),
            preserve_default=False,
        ),
    ]
