# Generated by Django 3.2.6 on 2022-02-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0014_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
    ]
