# Generated by Django 3.2.4 on 2021-07-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0015_alter_compiler_compile_cmd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compilerconfiguration',
            old_name='flags',
            new_name='cc_clags',
        ),
        migrations.AddField(
            model_name='compiler',
            name='assemble_cmd',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compilerconfiguration',
            name='as_flags',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
