# Generated by Django 3.2.4 on 2021-07-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0016_auto_20210707_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilerconfiguration',
            name='shortname',
        ),
    ]
