# Generated by Django 3.2.4 on 2021-07-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0017_remove_compilerconfiguration_shortname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compilerconfiguration',
            old_name='cc_clags',
            new_name='cc_flags',
        ),
    ]
