# Generated by Django 3.2.4 on 2021-07-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0018_rename_cc_clags_compilerconfiguration_cc_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scratch',
            name='context',
            field=models.TextField(blank=True),
        ),
    ]
