# Generated by Django 4.0.3 on 2022-03-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0018_rename_compilers'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratch',
            name='preset',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
