# Generated by Django 4.0.3 on 2022-04-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0019_scratch_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="compilerconfig",
            name="diff_flags",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="scratch",
            name="diff_flags",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
    ]
