# Generated by Django 3.2.4 on 2021-07-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0020_auto_20210727_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assembly',
            new_name='Asm',
        ),
    ]
