# Generated by Django 4.0.4 on 2022-06-12 07:32

import django.db.migrations.operations.special
from django.db import migrations


def unnull_diff_label(apps, schema_editor):
    Scratch = apps.get_model("coreapp", "Scratch")
    for row in Scratch.objects.all():
        if row.diff_label is None:
            row.diff_label = ""
            row.save(update_fields=["diff_label"])


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0021_diff_flags_default"),
    ]

    operations = [
        migrations.RunPython(
            code=unnull_diff_label,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
