# Generated by Django 3.2.4 on 2021-07-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0022_auto_20210729_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scratch',
            name='target_asm',
        ),
        migrations.AddField(
            model_name='scratch',
            name='target_assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.assembly'),
        ),
    ]
