# Generated by Django 4.0.5 on 2022-06-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0022_make_diff_label_non_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scratch",
            name="diff_label",
            field=models.CharField(blank=True, default="", max_length=512),
            preserve_default=False,
        ),
    ]
