# Generated by Django 3.2.4 on 2021-07-31 16:58

import coreapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0023_auto_20210801_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilation',
            name='asm',
        ),
        migrations.AddField(
            model_name='compilation',
            name='object',
            field=models.FilePathField(null=True, path=coreapp.models.compilation_objects_path),
        ),
    ]
