# Generated by Django 4.1 on 2022-08-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0024_remove_psyq_as_compiler"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pseudonym",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
