# Generated by Django 3.2.4 on 2021-07-31 16:59

import coreapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0024_auto_20210801_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='object',
            field=models.FilePathField(path=coreapp.models.compilation_objects_path),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='target_assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.assembly'),
        ),
    ]
