# Generated by Django 4.1 on 2022-09-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0025_profile_pseudonym"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectimportconfig",
            old_name="symbol_addrs_path",
            new_name="symbol_addrs_filename",
        ),
        migrations.AddField(
            model_name="projectimportconfig",
            name="include_dirs",
            field=models.TextField(blank=True, default="include"),
        ),
    ]
