# Generated by Django 3.2.5 on 2021-08-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0026_auto_20210803_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratch',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.profile'),
        ),
    ]
