# Generated by Django 4.1 on 2022-10-06 11:22

import coreapp.models.project
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0027_uploadable_project_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="icon",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=False,
                null=True,
                quality=100,
                scale=1.0,
                size=[256, 256],
                upload_to=coreapp.models.project.icon_path,
            ),
        ),
    ]
