# Generated by Django 3.2.6 on 2021-08-09 05:11


from django.conf import settings
from django.db import migrations, models
from django.utils.crypto import get_random_string
import logging
import os
from pathlib import Path


def asm_objects_path():
    return settings.BASE_DIR / "local_files" / "assemblies"


def compilation_objects_path():
    return settings.BASE_DIR / "local_files" / "compilations"


def forwards_fn(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    for model_name in ["Assembly", "Compilation"]:
        Model = apps.get_model("coreapp", model_name)
        for m in Model.objects.using(db_alias).iterator(chunk_size=100):
            # Read the object file from the filesystem and put it in the database
            object_path = Path(m.object)
            if object_path.exists():
                m.elf_object = object_path.read_bytes()
                m.save()
            else:
                logging.warning(
                    f"{model_name} object file {m.object} does not exist, leaving empty in DB"
                )


def reverse_fn(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    for model_name in ["Assembly", "Compilation"]:
        Model = apps.get_model("coreapp", model_name)
        for m in Model.objects.using(db_alias).iterator(chunk_size=100):
            # Read the object file from the database and write it to the filesystem
            filename = get_random_string(length=8) + ".o"
            object_path = Path(Model._meta.get_field("object").path()) / filename
            assert not object_path.exists(), f"{object_path} already exists"
            object_path.write_bytes(m.elf_object)
            m.object = object_path
            m.save()


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0027_scratch_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="assembly",
            name="elf_object",
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name="compilation",
            name="elf_object",
            field=models.BinaryField(blank=True),
        ),
        migrations.RunPython(forwards_fn, reverse_fn),
        # Allow the `object` fields to be blank, so that this migration can run in reverse
        migrations.AlterField(
            model_name="assembly",
            name="object",
            field=models.FilePathField(path=asm_objects_path, blank=True),
        ),
        migrations.AlterField(
            model_name="compilation",
            name="object",
            field=models.FilePathField(path=compilation_objects_path, blank=True),
        ),
        migrations.RemoveField(
            model_name="assembly",
            name="object",
        ),
        migrations.RemoveField(
            model_name="compilation",
            name="object",
        ),
    ]
