# Generated by Django 3.2.4 on 2021-08-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0028_auto_20210808_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratch',
            name='original_context',
            field=models.TextField(blank=True),
        ),
    ]
