# Generated by Django 3.2.4 on 2021-08-09 13:56

import coreapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0029_scratch_original_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='id',
        ),
        migrations.RemoveField(
            model_name='compilation',
            name='id',
        ),
        migrations.AddField(
            model_name='assembly',
            name='hash',
            field=models.CharField(default=0, max_length=64, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compilation',
            name='hash',
            field=models.CharField(default=0, max_length=64, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compilation',
            name='stderr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='slug',
            field=models.SlugField(default=coreapp.models.gen_scratch_id, primary_key=True, serialize=False),
        ),
    ]
