# Generated by Django 4.1.4 on 2022-12-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0029_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="compilerconfig",
            name="assembler_flags",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="scratch",
            name="compiler_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coreapp.compilerconfig",
            ),
        ),
    ]
