# Generated by Django 3.2.4 on 2021-08-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0028_object_into_db'),
        ('coreapp', '0030_auto_20210809_2256'),
    ]

    operations = [
    ]
