# Generated by Django 4.1.4 on 2022-12-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0031_auto_20221219_1944"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scratch",
            name="compiler",
        ),
        migrations.RemoveField(
            model_name="scratch",
            name="compiler_flags",
        ),
        migrations.RemoveField(
            model_name="scratch",
            name="diff_flags",
        ),
        migrations.RemoveField(
            model_name="scratch",
            name="platform",
        ),
        migrations.AlterField(
            model_name="scratch",
            name="compiler_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="coreapp.compilerconfig"
            ),
        ),
    ]
