# Generated by Django 4.2.3 on 2023-07-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0032_replace_ps2_991111_with_991111a"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratch",
            name="match_override",
            field=models.BooleanField(default=False),
        ),
    ]
