# Generated by Django 4.2.3 on 2023-09-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0037_rename_psyq43_to_psyq44"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratch",
            name="libraries",
            field=models.JSONField(default=list),
        ),
    ]
