# Generated by Django 4.2.5 on 2023-10-05 03:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0040_preset_remove_projectfunction_import_config_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="repo",
        ),
        migrations.DeleteModel(
            name="GitHubRepo",
        ),
    ]
