# Generated by Django 4.2.5 on 2023-10-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0041_preset_decompiler_flags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="repo",
        ),
        migrations.AlterField(
            model_name="preset",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="GitHubRepo",
        ),
    ]
