# Generated by Django 4.2.6 on 2023-10-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0042_remove_project_repo_alter_preset_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
