# Generated by Django 4.2.6 on 2023-10-24 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0044_populate_preset_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scratch",
            name="preset",
        ),
    ]
