# Generated by Django 4.2.6 on 2023-10-30 21:52

import coreapp.models.scratch
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0046_rename_preset_fk_scratch_preset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="diff_flags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="preset",
            name="libraries",
            field=coreapp.models.scratch.LibrariesField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="scratch",
            name="diff_flags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
