# Generated by Django 4.2.6 on 2023-11-01 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0047_alter_preset_diff_flags_alter_preset_libraries_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scratch",
            name="project_function",
        ),
        migrations.DeleteModel(
            name="ProjectFunction",
        ),
    ]
