# Generated by Django 5.0 on 2024-01-15 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0048_remove_scratch_project_function_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assembly",
            name="source_asm",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="coreapp.asm"
            ),
        ),
    ]
