# Generated by Django 5.0 on 2024-01-17 00:43

from django.db import migrations, models
from django.utils.crypto import get_random_string


def gen_claim_token() -> str:
    return get_random_string(length=32)


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0049_alter_assembly_source_asm"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratch",
            name="claim_token",
            field=models.CharField(default=gen_claim_token, max_length=64, null=True),
        ),
    ]
