# Generated by Django 5.0 on 2024-01-17 00:43

import coreapp.models.scratch
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0048_remove_scratch_project_function_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratch",
            name="claim_token",
            field=models.CharField(
                default=coreapp.models.scratch.gen_claim_token, max_length=64, null=True
            ),
        ),
    ]
