# Generated by Django 5.0.2 on 2024-02-15 14:54

from django.db import migrations, models
from django.utils.crypto import get_random_string

import coreapp.models.scratch


def gen_claim_token() -> str:
    return get_random_string(length=32)


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0050_scratch_claim_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compilerconfig",
            name="diff_flags",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="scratch",
            name="claim_token",
            field=models.CharField(
                blank=True,
                default=gen_claim_token,
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scratch",
            name="libraries",
            field=coreapp.models.scratch.LibrariesField(
                blank=True, default=list, null=True
            ),
        ),
    ]
