# Generated by Django 5.0.2 on 2024-02-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0050_scratch_claim_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubuser",
            name="api_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="githubuser",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="githubuser",
            name="html_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="githubuser",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
