# Generated by Django 5.0.2 on 2024-02-15 14:54

import coreapp.models.scratch
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0050_scratch_claim_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compilerconfig",
            name="diff_flags",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="scratch",
            name="claim_token",
            field=models.CharField(
                blank=True,
                default=coreapp.models.scratch.gen_claim_token,
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scratch",
            name="libraries",
            field=coreapp.models.scratch.LibrariesField(
                blank=True, default=list, null=True
            ),
        ),
    ]
