# Generated by Django 5.0.3 on 2024-05-08 19:59

import coreapp.models.comment
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0053_rename_mwcps2_compilers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "slug",
                    models.SlugField(
                        default=coreapp.models.comment.gen_comment_id,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField(max_length=5000)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="coreapp.profile",
                    ),
                ),
                (
                    "scratch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="coreapp.scratch",
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_time"],
            },
        ),
    ]
