# Generated by Django 5.0.3 on 2024-04-07 12:06

import django.db.migrations.operations.special
from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from coreapp.libraries import Library


def add_win32_platform_to_libraries(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """
    Currently only there is only a directx library and that is exclusive to the win32 platform.
    1. Add "platform" to the library
    2. Update any presets that use libraries to include "platform": "win32"

    3. Remove library from any non-win32 scratch
    """

    Scratch = apps.get_model("coreapp", "Scratch")

    # Add platform to win32 scratches
    for row in Scratch.objects.only("libraries").filter(platform="win32"):
        if len(row.libraries) > 0:
            # e.g. [{"name": "directx", "version": "8.0"}] -> [{"name": "directx", "version": "8.0", "platform": "win32"}]
            row.libraries = [
                Library(name=lib.name, version=lib.version, platform="win32")
                for lib in row.libraries
            ]
            row.save(update_fields=["libraries"])

    # Add platform to win32 presets
    Preset = apps.get_model("coreapp", "Preset")
    for row in Preset.objects.only("libraries").filter(platform="win32"):
        if len(row.libraries) > 0:
            # e.g. [{"name": "directx", "version": "8.0"}] -> [{"name": "directx", "version": "8.0", "platform": "win32"}]
            row.libraries = [
                Library(name=lib.name, version=lib.version, platform="win32")
                for lib in row.libraries
            ]
            row.save(update_fields=["libraries"])

    # Clear libraries for any non-win32 scratches that mistakenly have libraries assigned
    for row in Scratch.objects.only("libraries").exclude(platform="win32"):
        if len(row.libraries) > 0:
            row.libraries = []
            row.save(update_fields=["libraries"])


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0053_rename_mwcps2_compilers"),
    ]

    operations = [
        migrations.RunPython(
            code=add_win32_platform_to_libraries,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        )
    ]
