# Generated by Django 5.0.3 on 2024-05-10 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0054_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["creation_time"]},
        ),
    ]
