# Generated by Django 5.0.3 on 2024-05-23 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0054_presets_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="coreapp.profile",
            ),
        ),
    ]
