# Generated by Django 5.0.6 on 2024-05-26 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0055_alter_preset_owner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompilerConfig",
        ),
    ]
