# Generated by Django 5.1.7 on 2025-03-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0058_rename_gcc272sn_to_gcc272sn0004"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratch",
            name="decompiler_flags",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
    ]
