# Generated by Django 5.1.7 on 2025-05-29 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0060_populate_scratch_family"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="githubuser",
            name="access_token",
        ),
    ]
