# Generated by Django 5.1.7 on 2025-06-02 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0061_remove_githubuser_access_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_request_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
