# Generated by Django 5.2.8 on 2026-02-21 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0065_deduplicate_context"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scratch",
            name="context",
        ),
    ]
