# Generated by Django 5.2.11 on 2026-03-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0066_remove_scratch_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scratch",
            name="claim_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
