# Generated by Django 5.2.11 on 2026-03-13 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0067_alter_scratch_claim_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scratch",
            name="claim_token",
        ),
    ]
