# Generated by Codex on 2026-05-10

import logging
from typing import Any, NamedTuple

from django.apps.registry import Apps
from django.db import migrations, reset_queries, transaction
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.models import Q

logger = logging.getLogger(__name__)


class BestFork(NamedTuple):
    fork_id: str
    score: int
    max_score: int
    is_match: bool
    match_override: bool
    updated_at: Any


def scratch_is_match(scratch: Any) -> bool:
    return scratch.score == 0 or scratch.match_override


def scratch_has_score(scratch: Any) -> bool:
    return scratch.score >= 0


def scratch_has_usable_result(scratch: Any) -> bool:
    return scratch_has_score(scratch) or scratch.match_override


def scratch_improves(original: Any, candidate: Any) -> bool:
    if original.pk == candidate.pk:
        return False

    if not scratch_has_usable_result(candidate):
        return False

    candidate_is_match = scratch_is_match(candidate)
    if scratch_is_match(original):
        return (
            candidate_is_match
            and scratch_has_score(candidate)
            and (not scratch_has_score(original) or candidate.score < original.score)
        )

    if candidate_is_match:
        return True

    if not scratch_has_score(original):
        return True

    return candidate.score < original.score


def candidate_beats_record(candidate: Any, record: BestFork | None) -> bool:
    if record is None:
        return True

    candidate_is_match = scratch_is_match(candidate)
    if candidate_is_match != record.is_match:
        return candidate_is_match

    # If both are considered matches, prefer the lowest real score. A match
    # override with no score should not beat a real score.
    if not scratch_has_score(candidate):
        return False

    if record.score < 0:
        return True

    return candidate.score < record.score


def backfill_best_forks(
    apps: Apps,
    schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    Scratch = apps.get_model("coreapp", "Scratch")
    BestForkModel = apps.get_model("coreapp", "BestFork")

    chunk_size = 2_000
    best_by_scratch: dict[str, BestFork] = {}
    scratch_cache: dict[str, Any] = {}

    fields = [
        "slug",
        "parent_id",
        "score",
        "max_score",
        "match_override",
        "last_updated",
    ]

    def get_scratch(slug: str) -> Any:
        cached = scratch_cache.get(slug)
        if cached is not None:
            return cached

        scratch = Scratch.objects.only(*fields).get(pk=slug)
        scratch_cache[slug] = scratch
        return scratch

    def commit_records(records: list[Any]) -> None:
        if records:
            with transaction.atomic():
                BestForkModel.objects.bulk_create(records)
            reset_queries()
            records.clear()

    BestForkModel.objects.all().delete()

    qs = (
        Scratch.objects.filter(parent_id__isnull=False)
        .filter(Q(score__gte=0) | Q(match_override=True))
        .only(*fields)
    )

    processed = 0
    candidate_count = 0
    ancestor_count = 0
    override_vs_override_count = 0
    override_vs_override_examples: list[tuple[str, str, str]] = []
    match_override_candidate_count = 0
    match_override_candidate_examples: list[tuple[str, str]] = []
    for candidate in qs.iterator(chunk_size=chunk_size):
        processed += 1
        candidate_count += 1
        scratch_cache[candidate.pk] = candidate

        parent_id = candidate.parent_id
        seen: set[str] = set()
        while parent_id and parent_id not in seen:
            seen.add(parent_id)
            parent = get_scratch(parent_id)
            ancestor_count += 1

            if scratch_improves(parent, candidate):
                if scratch_is_match(parent) and scratch_is_match(candidate):
                    match_override_candidate_count += 1
                    if len(match_override_candidate_examples) < 10:
                        match_override_candidate_examples.append(
                            (parent.pk, candidate.pk)
                        )

                record = best_by_scratch.get(parent.pk)
                if (
                    record is not None
                    and candidate.match_override
                    and record.match_override
                ):
                    override_vs_override_count += 1
                    if len(override_vs_override_examples) < 10:
                        override_vs_override_examples.append(
                            (parent.pk, candidate.pk, record.fork_id)
                        )

                if candidate_beats_record(candidate, record):
                    best_by_scratch[parent.pk] = BestFork(
                        fork_id=candidate.pk,
                        score=candidate.score,
                        max_score=candidate.max_score,
                        is_match=scratch_is_match(candidate),
                        match_override=candidate.match_override,
                        updated_at=candidate.last_updated,
                    )

            parent_id = parent.parent_id

        if processed % chunk_size == 0:
            logger.info(
                "Processed %s fork candidates; checked %s ancestors; found %s improved scratches",
                f"{processed:,}",
                f"{ancestor_count:,}",
                f"{len(best_by_scratch):,}",
            )
            if len(scratch_cache) > chunk_size * 10:
                scratch_cache.clear()
            reset_queries()

    logger.info(
        "Finished processing %s fork candidates; checked %s ancestors; found %s improved scratches",
        f"{candidate_count:,}",
        f"{ancestor_count:,}",
        f"{len(best_by_scratch):,}",
    )
    logger.info(
        "Saw %s override-vs-override best-fork comparisons",
        f"{override_vs_override_count:,}",
    )
    logger.info(
        "Saw %s match-improving matched candidates",
        f"{match_override_candidate_count:,}",
    )
    if match_override_candidate_examples:
        logger.info(
            "Match-improving candidate examples: %s",
            ", ".join(
                f"scratch={scratch_id} candidate={candidate_id}"
                for scratch_id, candidate_id in match_override_candidate_examples
            ),
        )
    if override_vs_override_examples:
        logger.info(
            "Override-vs-override examples: %s",
            ", ".join(
                f"scratch={scratch_id} candidate={candidate_id} current_best={record_id}"
                for scratch_id, candidate_id, record_id in override_vs_override_examples
            ),
        )

    records = []
    created = 0
    for scratch_id, best in best_by_scratch.items():
        records.append(
            BestForkModel(
                scratch_id=scratch_id,
                fork_id=best.fork_id,
                score=best.score,
                max_score=best.max_score,
                is_match=best.is_match,
                created_at=best.updated_at,
                updated_at=best.updated_at,
            )
        )
        created += 1

        if len(records) >= chunk_size:
            commit_records(records)
            logger.info("Created %s BestFork rows", f"{created:,}")

    commit_records(records)
    logger.info("Finished creating %s BestFork rows", f"{created:,}")


# def delete_backfilled_best_forks(
#     apps: Apps,
#     schema_editor: BaseDatabaseSchemaEditor,
# ) -> None:
#     BestForkModel = apps.get_model("coreapp", "BestFork")
#     BestForkModel.objects.all().delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("coreapp", "0070_bestfork"),
    ]

    operations = [
        migrations.RunPython(
            backfill_best_forks,
            # delete_backfilled_best_forks,
        ),
    ]
