# Generated by Django 5.2.11 on 2026-06-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0071_backfill_bestfork"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="scratch",
            index=models.Index(fields=["-creation_time"], name="scratch_created_idx"),
        ),
        migrations.AddIndex(
            model_name="scratch",
            index=models.Index(fields=["-last_updated"], name="scratch_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="scratch",
            index=models.Index(fields=["score"], name="scratch_score_idx"),
        ),
    ]
