# Generated by Django 6.1.1 on 2026-10-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0072_add_indexes_to_scratch_sort_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScratchPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("help_wanted", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scratch_preferences",
                        to="coreapp.profile",
                    ),
                ),
                (
                    "scratch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="coreapp.scratch",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scratch", "profile"),
                        name="unique_scratch_preference",
                    )
                ],
            },
        ),
    ]
