# Generated by Django 6.1.1 on 2026-10-06 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0073_scratchpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScratchUserAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('help_wanted', models.BooleanField(default=False)),
                ('help_wanted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='scratchpreference',
            name='unique_scratch_preference',
        ),
        migrations.AddField(
            model_name='scratchuserattribute',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_user_attributes', to='coreapp.profile'),
        ),
        migrations.AddField(
            model_name='scratchuserattribute',
            name='scratch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attributes', to='coreapp.scratch'),
        ),
        migrations.RemoveField(
            model_name='scratchpreference',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='scratchpreference',
            name='scratch',
        ),
        migrations.AddConstraint(
            model_name='scratchuserattribute',
            constraint=models.UniqueConstraint(fields=('scratch', 'profile'), name='unique_scratch_user_attribute'),
        ),
        migrations.DeleteModel(
            name='ScratchPreference',
        ),
    ]
