# Generated by Django 6.1.1 on 2026-10-06

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def backfill_help_wanted_timestamps(apps, schema_editor):
    ScratchUserAttribute = apps.get_model("coreapp", "ScratchUserAttribute")
    ScratchUserAttribute.objects.filter(
        help_wanted=True,
        help_wanted_at__isnull=True,
    ).update(help_wanted_at=timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0073_scratchpreference"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scratchpreference",
            name="unique_scratch_preference",
        ),
        migrations.RenameModel(
            old_name="ScratchPreference",
            new_name="ScratchUserAttribute",
        ),
        migrations.AlterField(
            model_name="scratchuserattribute",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scratch_user_attributes",
                to="coreapp.profile",
            ),
        ),
        migrations.AlterField(
            model_name="scratchuserattribute",
            name="scratch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_attributes",
                to="coreapp.scratch",
            ),
        ),
        migrations.AddField(
            model_name="scratchuserattribute",
            name="help_wanted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(
            backfill_help_wanted_timestamps,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="scratchuserattribute",
            constraint=models.UniqueConstraint(
                fields=("scratch", "profile"),
                name="unique_scratch_user_attribute",
            ),
        ),
    ]
