# Generated by Django 6.1.1 on 2026-10-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0074_rename_scratchpreference"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scratchuserattribute",
            name="unique_scratch_user_attribute",
        ),
        migrations.RenameModel(
            old_name="ScratchUserAttribute",
            new_name="ScratchFlags",
        ),
        migrations.AlterField(
            model_name="scratchflags",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scratch_flags",
                to="coreapp.profile",
            ),
        ),
        migrations.AlterField(
            model_name="scratchflags",
            name="scratch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flags",
                to="coreapp.scratch",
            ),
        ),
        migrations.AddConstraint(
            model_name="scratchflags",
            constraint=models.UniqueConstraint(
                fields=("scratch", "profile"),
                name="unique_scratch_flags",
            ),
        ),
    ]
