name: Chores

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Update m2c & asm-differ
        run: cd backend && poetry update m2c asm-differ

      - name: Commit changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "🤖 (chore): bump m2c & asm-differ to latest"
          title: "🤖 (chore): bump m2c & asm-differ to latest"
          branch: "update-m2c-asm-differ"
          delete-branch: true
