name: Chores

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    if: github.repository == 'decompme/decomp.me'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Update m2c & asm-differ
        run: cd backend && uv sync --upgrade-package m2c asm-differ

      - name: Check for changes
        run: |
          if git diff --quiet HEAD; then
            echo "No changes to commit."
            exit 0
          fi

      - name: Commit changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "🤖 (chore): bump m2c / asm-differ to latest"
          title: "🤖 (chore): bump m2c / asm-differ to latest"
          branch: "update-m2c-asm-differ"
          delete-branch: true
          committer: "GitHub Actions <actions@github.com>"
          author: "GitHub Actions <actions@github.com>"
